#!/bin/bash

# Define command-line arguments

RESOURCE_TYPE=$1
NAMESPACE=$2

if [[ ! "$RESOURCE_TYPE" ]]
then
    echo Resource type must be provided as first argument
    exit 1
fi

if [ "$RESOURCE_TYPE" != "pod" ] && [ "$RESOURCE_TYPE" != "node" ]
then
    echo Resource type can be either 'pod' or 'node'
    exit 1
fi

if [[ ! "$NAMESPACE" ]]
then
    echo Namespace must be provided as second argument
    exit 1
fi

printLine () {
  printf $1
  printf '%.s──' {1..26}
  printf $2
  printf '%.s──' {1..9}
  printf $3
  printf '%.s──' {1..6}
  printf $4
  printf '%.s──' {1..6}
  printf $5
  printf '\n'
}

formatColumns () {
  printf "│ %-50s │ %-16s │ %-10s │ %-10s │\n" $1 $2 $3 $4
}

printLine "┌" "┬" "┬" "┬" "┐"

formatColumns "Resource" "Namespace" "CPU" "Memory"

printLine "├" "┼" "┼" "┼" "┤"

# Retrieve resource usage statistics from Kubernetes
kubectl top $RESOURCE_TYPE -n $NAMESPACE | tail -n +2 | while read line
do
  # Extract CPU and memory usage from the output
  NAME=$(echo $line | awk '{print $1}')
  CPU=$(echo $line | awk '{print $2}')

  case "$RESOURCE_TYPE" in
    "pod")
        MEMORY=$(echo $line | awk '{print $3}') ;;
    "node")
        MEMORY=$(echo $line | awk '{print $4}') ;;
    *)
        echo "Unknown resorce type" ;;
  esac

  # Output the statistics to the console
  formatColumns $NAME $NAMESPACE $CPU $MEMORY
done

printLine "└" "┴" "┴" "┴" "┘"
